### ISSUE TITLE
emacs-workspaces/project-switch-project-open-file vs emacs-workspaces/open-existing-project-and-workspace

### ISSUE THREAD

**Issue by mfiano** [mclear-tools/emacs-workspaces#2] opened 2022-03-07 19:18 UTC
This is just a question, but could you perhaps explain what each function does? I can't tell what the difference is between these two functions from their names or by invoking them...they both seem to have the same effect for me, unless I'm missing something. It might be a good idea to write descriptions in the README, or to word the documentation a bit better to avoid any confusion. Thanks!

**Comment by mclearc** [comment] 2022-03-07 19:39
The main difference is that `emacs-workspaces/open-existing-project-and-workspace` also renames the tab with ` (tab-bar-rename-tab (emacs-workspaces--name-tab-by-project-or-default)`, which gives a cleaner tab-name than tab bar had been doing on its own. But I should probably remove `emacs-workspaces/project-switch-project-open-file` (at least as an interactive function) in favor of `emacs-workspaces/switch-to-or-create-workspace`.

**Comment by mfiano** [comment] 2022-03-07 19:40
That makes sense. Thanks for the quick reply!

**Comment by mclearc** [comment] 2022-03-07 19:59
Oh - and one other thing worth noting: `emacs-workspaces/project-switch-project-open-file` doesn't actually open a new workspace, it just opens a new project and bypasses `project.el`'s command menu in favor of opening a file via completing-read (which is a bit more `projectile.el` like). But since it largely reproduces `project-switch-project` I will likely remove it as unnecessary.

**Comment by mfiano** [comment] 2022-03-07 20:04
Yes, that makes sense. I think it might also be worth integrating the interactive project.el menu into this project somehow. I really like how it is more projectile-like, but I don't like that I can't restore window configurations with [project-tab-groups](https://github.com/fritzgrabo/project-tab-groups). Maybe there is a way to allow these two packages to play well together, for those that would like to restore their persistent project window configurations upon loading a project?

**Comment by mclearc** [comment] 2022-03-07 20:09
> Yes, that makes sense. I think it might also be worth integrating the interactive project.el menu into this project somehow. I really like how it is more projectile-like, but I don't like that I can't restore window configurations with [project-tab-groups](https://github.com/fritzgrabo/project-tab-groups). 

Yes -- in general I would like to incorporate tab-group functionality from `tab-bar` into this package. I just need to find some time...

> Maybe there is a way to allow these two packages to play well together, for those that would like to restore their persistent project window configurations upon loading a project?

Have you seen Daniel Mendler's package [tab-bookmark](https://github.com/minad/tab-bookmark)? It might be helpful here.

**Comment by mfiano** [comment] 2022-03-07 20:12
> Have you seen Daniel Mendler's package [tab-bookmark](https://github.com/minad/tab-bookmark)? It might be helpful here.

I haven't seen this one! I'll check it out.

**Comment by mfiano** [comment] 2022-03-07 20:14
I just discovered a potential problem with your code. I will open a new issue. I really like this project as I don't like the extra interactive menu step of plain old project.el and therefor the other packages that extend this menu. Good work!

**Comment by mfiano** [comment] 2022-03-07 20:39
Oops, I mistakenly referenced `project-tab-groups` above. That is not the package that allows restoring project window configurations. It is [project-x](https://github.com/karthink/project-x) for those confused readers out there :) Long day configuring Emacs and researching various packages, please forgive me :)

**Comment by mclearc** [comment] 2022-03-08 06:27
Closed via https://github.com/mclear-tools/emacs-workspaces/commit/09aa2755460537c94b90735417a00e263f4eaf8a

**Closed by mclearc** 2022-03-08 06:27 UTC
